### PR TITLE
Bam group by speedup

### PR DESCRIPTION
**Pull request by Lioscro**
Using `hits.utilities.group_by` happens to be very slow for some reason, so I implemented our own `group_bam_by_key` function, which achieves approx. 100x speedup.

Branches from `remove-intbc-logging` #163

### CODE REVIEW

**Comment by colganwi** [comment]
For me this PR does not speedup `cas.pp.collapse` at all. @Lioscro can you provide a test case or more details about the compute environment? Maybe this is faster with memory constraints?

**Comment by Lioscro** [comment]
It's been a hot minute since I've worked on this, so I'm having a hard time providing any additional context, but I believe the speedup was achieved for very large BAMs.

But given my limited recollection, I'd trust your experience more than whatever I can remember, so I'm fine if you decide this PR is no longer needed.

**Comment by colganwi** [comment]
I tested with a 15GB bam file and see a 2X speed up. MD5 checksums of the outputs are the same. Nice work @Lioscro!

**Review by colganwi — APPROVED** [review]
Looks good to me!

**Pull request merged**
